knp_menu:
  # use "twig: false" to disable the Twig extension and the TwigRenderer
  twig:
    template: '@KnpMenu/menu.html.twig'
  #  if true, enables the helper for PHP templates
  templating: false
  # the renderer to use, list is also available by default
  default_renderer: twig
  # Disable some to improve performance
  providers:
    builder_alias: false    # disable the builder-alias-based provider
    builder_service: false
    container_aware: true   # keep this one enabled. Can be omitted as it is the default
