vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /uploads/images/users
            upload_destination: '%kernel.project_dir%/public/uploads/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'id', transliterate: true}